version: "3.9"

services:

  backend:
    build: ./backend-service
    ports:
      - "8081:8081"
    networks:
      - cs335-net

  gateway-1:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - BACKEND_URL=http://backend:8081/api/
      # redis matches the service name already defined in docker-compose
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - METRICS_EXPORT_PATH=/data/metrics-exports
    volumes:
      - gateway1-exports:/data/metrics-exports
    depends_on:
      - backend
      - redis
    networks:
      - cs335-net

  gateway-2:
    build: ./api-gateway
    ports:
      - "8082:8080"
    environment:
      - BACKEND_URL=http://backend:8081/api/
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - METRICS_EXPORT_PATH=/data/metrics-exports
    volumes:
      - gateway2-exports:/data/metrics-exports
    depends_on:
      - backend
      - redis
    networks:
      - cs335-net

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes", "--save", "60", "1000"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - cs335-net

networks:
  cs335-net:
    driver: bridge

volumes:
  redis-data:
  gateway1-exports:
  gateway2-exports:
