services:

  backend:
    build: ./backend-service
    ports:
      - "8081:8081"
    # These environment variables allow the backend to connect to Redis.
    # The backend will use these to connect to the Redis service for storing logs and metrics.  
    environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - cs335-net

  # --- Node 1 ---
  gateway1:
    build: ./api-gateway
    ports:
      - "8080:8080" # Host 8080 -> Container 8080
    environment:
      - GATEWAY_ID=gateway-1
      - BACKEND_URL=http://backend:8081/api/
      # redis matches the service name already defined in docker-compose
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      backend:
        condition: service_started
      redis:
        condition: service_healthy
    networks:
      - cs335-net

  # Shared Memory (Redis): Because the REDIS_HOST=redis is identical for both, 
  # they share the Blacklist and the Rate Limit Buckets counters.
  # --- Node 2 ---  
  gateway2:
    build: ./api-gateway
    ports:
      - "8082:8080" # Host 8082 -> Container 8080 (same container port as gateway1)
    environment:
      - GATEWAY_ID=gateway-2
      - BACKEND_URL=http://backend:8081/api/
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      backend:
        condition: service_started
      redis:
        condition: service_healthy
    networks:
      - cs335-net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - cs335-net
volumes:
  redis-data:

networks:
  cs335-net:
    driver: bridge
